#
# Makefile for the input misc drivers.
#

# Each configuration option enables a list of files.
# Z380C Sensor 
obj-$(CONFIG_SENSORS_BMC156_Z380C)    += BMC156_Z380C/

# Z380C SR/ER Light Sensor
obj-$(CONFIG_SENSORS_CM36686)   += CM36686/

# Z380C PR Light Sensor
obj-$(CONFIG_SENSORS_AP3425)   += AP3425/


# Z300CG Sensor
obj-$(CONFIG_SENSORS_BMC156_Z300CG)    += BMC156_Z300CG/
obj-$(CONFIG_SENSORS_AL3320A)   += AL3320A/

obj-$(CONFIG_HALL_SENSOR) += hall/
