#
#  Copyright (c) 2013, ASUSTek, Inc. All Rights Reserved.
#  Written by chris chang chris1_chang@asus.com
#

obj-y 	+= bq27520_battery_core.o  \
		asus_battery_power.o \
		asus_battery_proc_fs.o \
		bq27520_factory_data.o \
		bq27520_battery_upt_i2c.o